config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers:{ sessions: "users/sessions", registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks"}



  resources :wishlists, only:[:index, :create, :update] do
    get :clear, on: :collection
  end

  resources :carts do
    get :remove, on: :member
  end

  resources :orders, only: [:index, :show, :destroy, :create, :new]


  resources :products, only:[:show] do

  end

  get '/:category/:sub_category'=>'products#index', as: :category_products
  get '/:brand'=>'products#index', as: :brand_products



  resources :posts






  resources :reviews



  root 'home#index'
end

app/views/shared/_brands.html.erb
<div class="brands-name">
  <ul class="nav nav-pills nav-stacked">
    <% global_brands.each  do |brand| %>
        <li>
          <%= link_to brand_products_path(brand.name) do %>
              <span class="pull-right"> (<%= brand.products.count if brand.products.present? %>) </span><%= brand.name %>
          <% end %>
          <a href="#"> </a>
        </li>
    <% end %>
  </ul>
</div>

app/views/shared/_cart_header.html.erb
<h2>Cart</h2>
<%= link_to '', remove_cart_path(current_cart), remote: true, class: "cd-item-remove cd-img-replace" %>

app/views/shared/_cart_item.html.erb
<% if current_cart.cart_items.present? %>
    <% current_cart.cart_items.each do |cart_item| %>
        <% if cart_item.quantity > 0 %>
            <li>
              <span class="cd-qty"><%= cart_item.quantity %>x</span> <%= cart_item.product.name %>
              <div class="cd-price"> &#2547; <%= cart_item.product.price * cart_item.quantity %></div>
              <%= link_to '', cart_path(cart_item) , remote: true, method: :delete, class:" cd-item-remove cd-img-replace " %>
            </li>
        <% end %>
    <% end %>
<% else %>
    <hr/>
    <h3 class="text-center"> Cart Empty!</h3>
    <hr/>
<% end %>

app/views/shared/_categories.html.erb
<% global_categories.each do |category| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordian" href="#<%= category.name.downcase %>">
            <% if category.sub_categories.present? %>
                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
            <% end %>
            <%= category.name %>
          </a>
        </h4>
      </div>
      <div id="<%= category.name.downcase %>" class="panel-collapse collapse reset-padding">
        <div class="panel-body">
          <ul class="reset-margin">
            <% category.sub_categories.each do |sub_category| %>
                <li>
                  <%= link_to category_products_path(category.name, sub_category.name) do%>
                      <%= sub_category.name %>
                  <% end %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
<% end %>

app/views/shared/_current_user_profile_menu.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <span class="glyphicon glyphicon-user"></span>
    <strong><%= current_user.first_name %></strong>
    <span class="glyphicon glyphicon-chevron-down"></span>
  </a>
  <ul class="dropdown-menu user-dropdown">
    <li>
      <div class="navbar-login">
        <div class="row">
          <div class="col-lg-4">
            <p class="text-center">
              <span class="glyphicon glyphicon-user icon-size"></span>
            </p>
          </div>
          <div class="col-lg-8">
            <p class="text-left"><strong> <%= current_user.full_name %></strong></p>
            <p class="text-left small"><%= current_user.email %> </p>
            <p class="text-left">
              <%= link_to 'Profile', edit_user_registration_path,  class: 'btn btn-primary btn-block btn-sm' %>
            </p>
          </div>
        </div>
      </div>
    </li>
    <li class="divider navbar-login-session-bg"></li>
    <!--<li class="divider"></li>-->
    <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
          Sign Out <span class="glyphicon glyphicon-log-out pull-right"></span>
      <% end %>
    </li>
  </ul>
</li>

app/views/shared/_fixed_cart.html.erb
<div id="cd-cart-trigger">
  <span class="badge"> <%= current_cart_items %> </span>
  <i class="fa fa-shopping-cart fa-2x"></i>
</div>
<div id="cd-shadow-layer"></div>
<div id="cd-cart">
  <div class="cart-header" id="cart-header">
    <%= render 'shared/cart_header' %>
  </div>

  <ul id="cart-items" class="cd-cart-items">
    <%= render 'shared/cart_item' %>
  </ul> <!-- cd-cart-items -->

  <div class="cd-cart-total" id="total-cart">
    <%= render 'shared/total_cart' %>
  </div> <!-- cd-cart-total -->
  <% if user_signed_in? %>
      <%= link_to 'Checkout', orders_path(cart: current_cart), method: :post, class: 'checkout-btn' %>
  <% end %>

  <p class="cd-go-to-cart">
    <%= link_to 'Go to cart page', carts_path %>
  </p>
</div> <!-- cd-cart -->

app/views/shared/_flash.html.erb
<script type="text/javascript">
    $(function(){
        <% flash.each do |name, msg| -%>
            $.notify("<%=raw msg %>", "<%= name %>");
        <% end -%>
    });
</script>

app/views/shared/_footer.html.erb
<!-- CTA -->
<section id="cta" class="footer-wrapper style3">
  <h2>Sed faucibus et consequat</h2>
  <ul class="actions">
    <li><a href="#" class="button big">Get Started</a></li>
  </ul>
</section>

<!-- Footer -->
<footer id="footer">
  <ul class="icons">
    <li><a href="#" class="fa fa-twitter"><span class="label">Twitter</span></a></li>
    <li><a href="#" class="fa fa-facebook"><span class="label">Facebook</span></a></li>
    <li><a href="#" class="fa fa-instagram"><span class="label">Instagram</span></a></li>
    <li><a href="#" class="fa fa-dribbble"><span class="label">Dribbble</span></a></li>
    <li><a href="#" class="fa fa-envelope"><span class="label">Envelope</span></a></li>
  </ul>
  <ul class="menu">
    <li><a href="#">FAQ</a></li>
    <li><a href="#">Terms of Use</a></li>
    <li><a href="#">Privacy</a></li>
    <li><a href="#">Contact</a></li>
  </ul>
				<span class="copyright">
					&copy; Copyright. All rights reserved. Design by <a href="http://www.html5webtemplates.co.uk">RocketSofts</a>
				</span>
</footer>

app/views/shared/_header.html.erb
<header class="cd-main-header">
  <%= link_to root_path, class: 'cd-logo' do %>
        <%= image_tag 'brand_logo.png' %>
  <% end %>
  <div class="cd-search is-hidden">
    <form action="#0">
      <input type="search" placeholder="Search...">
    </form>
  </div> <!-- cd-search -->

  <a href="#0" class="cd-nav-trigger">
    <span></span>
  </a>

  <nav class="cd-nav">
    <ul class="cd-top-nav">
      <% if user_signed_in? %>
          <li>
            <%= link_to  wishlists_path do %>
              <i class="fa fa-hear"></i> Wishlist
            <% end %>
          </li>
          <li>
            <%= link_to 'Orders', orders_path %>
          </li>
          <li class="has-children account">
            <a href="#0">
              <i class="fa fa-user" ></i>
              Account
            </a>
            <ul>
              <li>
                <%= link_to 'My Account', edit_user_registration_path %>
              </li>
              <li>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
      <% else %>
          <li>
            <%= link_to new_user_session_path, remote: true do %>
              <i class="fa fa-sign-in" aria-hidden="true"></i>
              Login
            <% end %>
          </li>
      <% end %>
    </ul>
  </nav>
</header> <!-- .cd-main-header -->

app/views/shared/_modal.html.erb
<div class="modal fade login in" id="loginModal"  aria-hidden="false">
  <div class="modal-dialog login animated">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/shared/_products_list.html.erb
<% if products.present? %>
    <ul class="product-list-small">
      <% products.each do |product| %>
          <li>
            <%= link_to product_path(product), class:'product-photo' do%>
                <%= image_tag( product.image.present? ? product.image_url(:thumb) : "default_product_icon.png"  ) %>
            <% end %>

            <h2><%= link_to product.name.upcase , product_path(product), class:'product-photo' %></h2>

            <a href="#" class="product-compare">compare</a>

            <div class="product-rating">
              <div>
            <span class="product-stars" style="width: 60px" >
                <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
            </span>
              </div>
              <span><a href="#">82 reviews</a></span>
            </div>

            <p class="product-description">
              <%= truncate(product.description, length: 50) %>
            </p>

            <% if product.is_available %>
                <div class="btn-group add-to-cart" role="group" id="add-to-cart-<%= product.id %>">
                  <%=raw add_to_cart_text(product) %>
                </div>
            <% else %>
                <span class="product-out-of-stock">Out of stock</span>
            <% end %>
            <p class="product-price"> &#2547; <%= product.price %></p>

          </li>
      <% end %>
    </ul>
<% else %>
    <div class="no-products">
      <div class="no-products-message">
        <h2>There's no products. Please explore another category or brand..</h2>
      </div>
    </div>
<% end %>

app/views/shared/_side_nav.html.erb
<nav class="cd-side-nav">
  <ul>
    <li class="cd-label">Main</li>
    <li class="has-children overview <%= activation_checker(root_path)  %>">
      <%= link_to 'Homepage', root_path %>
    </li>
    <% global_categories.each do |category| %>
        <li class="has-children notifications <%= activation_checker(category_products_path(category.name, 'category'))  %>">
          <a href="javascript:void(0)"><%= category.name %></a>

          <ul>
            <% category.sub_categories.each do |sub_category| %>
                <li>
                  <%= link_to category_products_path(category.name, sub_category.name) do%>
                      <%= sub_category.name %>
                  <% end %>
                </li>
            <% end %>
          </ul>
        </li>
    <% end %>

  </ul>
  <ul>
    <li class="cd-label">Brand</li>
    <li>
      <input type="range" name="range_filter">
    </li>
  </ul>

  <ul>
    <li class="cd-label">Brand</li>
    <% global_brands.each do |brand| %>
        <li class="has-children bookmarks <%= activation_checker(brand_products_path(brand.name)) %>">
          <%= link_to brand_products_path(brand.name) do %>
            <%= brand.name %>
          <% end %>
        </li>
    <% end %>
  </ul>

  <ul>
    <li class="cd-label">Action</li>
    <li class="action-btn"><a href="#0">+ Button</a></li>
  </ul>
</nav>

app/views/shared/_slider.html.erb
<!--<div id="mi-slider" class="mi-slider">-->
  <!--<ul>-->
    <!--<li><a href="#"><img src="images/1.jpg" alt="img01"><h4>Boots</h4></a></li>-->
    <!--<li><a href="#"><img src="images/2.jpg" alt="img02"><h4>Oxfords</h4></a></li>-->
    <!--<li><a href="#"><img src="images/3.jpg" alt="img03"><h4>Loafers</h4></a></li>-->
    <!--<li><a href="#"><img src="images/4.jpg" alt="img04"><h4>Sneakers</h4></a></li>-->
  <!--</ul>-->
  <!--<ul>-->
    <!--<li><a href="#"><img src="images/5.jpg" alt="img05"><h4>Belts</h4></a></li>-->
    <!--<li><a href="#"><img src="images/6.jpg" alt="img06"><h4>Hats &amp; Caps</h4></a></li>-->
    <!--<li><a href="#"><img src="images/7.jpg" alt="img07"><h4>Sunglasses</h4></a></li>-->
    <!--<li><a href="#"><img src="images/8.jpg" alt="img08"><h4>Scarves</h4></a></li>-->
  <!--</ul>-->
  <!--<ul>-->
    <!--<li><a href="#"><img src="images/9.jpg" alt="img09"><h4>Casual</h4></a></li>-->
    <!--<li><a href="#"><img src="images/10.jpg" alt="img10"><h4>Luxury</h4></a></li>-->
    <!--<li><a href="#"><img src="images/11.jpg" alt="img11"><h4>Sport</h4></a></li>-->
  <!--</ul>-->
  <!--<ul>-->
    <!--<li><a href="#"><img src="images/12.jpg" alt="img12"><h4>Carry-Ons</h4></a></li>-->
    <!--<li><a href="#"><img src="images/13.jpg" alt="img13"><h4>Duffel Bags</h4></a></li>-->
    <!--<li><a href="#"><img src="images/14.jpg" alt="img14"><h4>Laptop Bags</h4></a></li>-->
    <!--<li><a href="#"><img src="images/15.jpg" alt="img15"><h4>Briefcases</h4></a></li>-->
  <!--</ul>-->
  <!--<nav>-->
    <!--<a href="#">Shoes</a>-->
    <!--<a href="#">Accessories</a>-->
    <!--<a href="#">Watches</a>-->
    <!--<a href="#">Bags</a>-->
  <!--</nav>-->
<!--</div>-->

<!--<script type="text/javascript">-->
<!--//    $(function(){-->
<!--//        $( '#mi-slider' ).catslider();-->
<!--//    });-->
<!--</script>-->

app/views/shared/_total_cart.html.erb
<p>Total <span> &#2547;  <%= total_price %></span></p>