config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers:{ sessions: "users/sessions", registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks"}



  resources :wishlists, only:[:index, :create, :update] do
    get :clear, on: :collection
  end

  resources :carts do
    get :remove, on: :member
  end

  resources :orders, only: [:index, :show, :destroy, :create, :new]


  resources :products, only:[:show] do

  end

  get '/:category/:sub_category'=>'products#index', as: :category_products
  get '/:brand'=>'products#index', as: :brand_products



  resources :posts






  resources :reviews



  root 'home#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  def add_product(product_id, item)
    cart_item = cart_items.find_by_product_id(product_id)
    if cart_item
      cart_item.quantity = cart_item.quantity.to_i + item.to_i
    else
      cart_item = cart_items.build(product_id: product_id, quantity: item)
    end
    cart_item
  end

  def total_cart_price
    self.cart_items.collect { |ci| ci.quantity * ci.product.price }.sum
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  # GET /carts
  # GET /carts.json
  def index
    @carts = current_cart.cart_items
  end


  # POST /carts
  # POST /carts.json
  def create
    cart = current_cart
    item = 1
    if params[:item].present?
      item = params[:item]
    end
    @cart_item = cart.add_product(params[:product], item)
    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to :back, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
        format.js
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    if params[:incr] == 'true'
      @cart_item.quantity += 1
    else
      if @cart_item.quantity >= 1
        @cart_item.quantity -= 1
      end
    end
    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  #remove cart from Cart and CartItem
  def remove
    @cart = Cart.find(params[:id])
    @cart_items = CartItem.where(cart_id: @cart.id)
    @cart_items.each do |cart|
      cart.destroy
    end
    session.delete(:@cart)
    @cart.destroy
    respond_to do |format|
      format.js
      format.html
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart_item = CartItem.find(params[:id])
    end

  def set_product(product)
    Product.find_by_id(product)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit!
    end
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :items %><br>
    <%= f.number_field :items %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.text_field :total_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/create.js.erb
$('#cd-cart-trigger').find('.badge').html('<%=  current_cart_items.to_i  %>');
$('#cart-items').html('<%= escape_javascript( render 'shared/cart_item' ).html_safe %>');
$('#total-cart').html('<%= escape_javascript( render 'shared/total_cart').html_safe %>');
$('#add-to-cart-<%= params[:product] %>').html('<%= escape_javascript( add_to_cart_text( @cart_item.product )  ).html_safe %>');

app/views/carts/destroy.js.erb
$('#cart-item-<%= @cart_item.id %>').remove();
$('#cd-cart-trigger').find('.badge').html('<%=  current_cart_items.to_i  %>');
$('#cart-items').html('<%= escape_javascript( render 'shared/cart_item' ).html_safe %>');
$('#total-cart').html('<%= escape_javascript( render 'shared/total_cart').html_safe %>');
$('#cart-header').html('<%= escape_javascript( render 'shared/cart_header' ).html_safe %>');
$('#add-to-cart-<%= @cart_item.product_id %>').html('<%= escape_javascript( add_to_cart_text( @cart_item.product )  ).html_safe %>');

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<section id="cart_items">
 <div class="panel panel-default">
   <div class="panel-body">
     <div class="page-header">
       <h3>Carts items</h3>
       <div class="actions">
         <%= link_to remove_cart_path(current_cart), remote: true, class: 'btn btn-danger reset-border-radius' do %>
             <i class="fa fa-trash"></i>
          <% end %>

       </div>
     </div>
     <div class="cart_info">
       <% if @carts.present? %>
           <table class="table table-responsive table-condensed">
             <thead>
             <tr class="cart_menu">
               <td class="image">Item</td>
               <td class="description">Description</td>
               <td class="price">Price</td>
               <td class="quantity">Quantity</td>
               <td class="total">Total</td>
               <td></td>
             </tr>
             </thead>
             <tbody id="cart_showcase">
             <% @carts.each do |cart| %>
                 <% if cart.quantity > 0 %>
                     <tr id="cart-item-<%= cart.id %>">
                       <td class="cart_product">
                         <%= link_to product_path(cart.product) do%>
                             <%= image_tag( cart.product.image_url.present? ? cart.product.image_url(:small_thumb) : 'default_product_icon.png' ) %>
                         <% end %>
                       </td>
                       <td class="cart_description">
                         <h4>
                           <%= link_to product_path(cart.product) do%>
                               <%= cart.product.name %>
                           <% end %>
                         </h4>
                         <p>
                           <%= cart.product.u_id %>
                         </p>
                       </td>
                       <td class="cart_price">
                         <p>
                           &#2547; <%= cart.product.price %>
                         </p>
                       </td>
                       <td class="cart_quantity">
                         <div class="btn-group add-to-cart" role="group" id="add-to-cart-<%= cart.product_id %>">
                           <%=raw add_to_cart_text(cart.product) %>
                         </div>
                       </td>
                       <td class="cart_total">
                         <p class="cart_total_price">
                           &#2547; <%= cart.product.price * cart.quantity %>
                         </p>
                       </td>
                       <td class="cart_delete">
                         <%= link_to cart_path(cart), remote: true, method: :delete, class:'cart_quantity_delete' do%>
                             <i class="fa fa-times"></i>
                         <% end %>
                       </td>
                     </tr>
                 <% end %>
             <% end %>
             <tr>
               <td class="cart_product"> Total </td>
               <td></td>
               <td class='cart_price'></td>
               <td></td>
               <td class="cart_total">
                 <p class="cart_total_price">
                   &#2547; <%= total_price %>
                 </p>
               </td>
               <td></td>
             </tr>
             </tbody>
           </table>
           <div class="text-center">
             <%= place_order_link %>
           </div>
       <% else %>
            <div class="alert alert-info">
              <h2 class="text-center">No item found</h2>
            </div>
       <% end %>
     </div>
   </div>
 </div>


</section> <!--/#cart_items-->

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/remove.js.erb
$('#cart_showcase').html('');
$('#cart-badge').find('.badge-notify').html('<%= current_cart_items.to_i %>');
$('#cart-header').html('<%= escape_javascript( render 'shared/cart_header' ).html_safe %>');
$('#cd-cart-trigger').find('.badge').html('<%=  current_cart_items.to_i  %>');
$('#cart-items').html('<%= escape_javascript( render 'shared/cart_item' ).html_safe %>');
$('#total-cart').html('<%= escape_javascript( render 'shared/total_cart').html_safe %>');
<% @cart_items.each do |cart_item| %>
$('#add-to-cart-<%= cart_item.product_id %>').html('<%= escape_javascript( add_to_cart_text( cart_item.product )  ).html_safe %>');
<% end %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @cart.product_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @cart.order_id %>
</p>

<p>
  <strong>Items:</strong>
  <%= @cart.items %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @cart.total_price %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/carts/update.js.erb
<% unless @cart_item.errors.present? %>
$('#cart-item-<%= @cart_item.id %>').find('.cart_quantity_input').val(<%= @cart_item.quantity %>);
$('#cd-cart-trigger').find('.badge').html('<%=  current_cart_items.to_i  %>');
$('#cart-items').html('<%= escape_javascript( render 'shared/cart_item' ).html_safe %>');
$('#total-cart').html('<%= escape_javascript( render 'shared/total_cart').html_safe %>');
$('#add-to-cart-<%= @cart_item.product_id %>').html('<%= escape_javascript( add_to_cart_text( @cart_item.product )  ).html_safe %>');
<% end %>