config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers:{ sessions: "users/sessions", registrations: 'users/registrations', :omniauth_callbacks => "users/omniauth_callbacks"}



  resources :wishlists, only:[:index, :create, :update] do
    get :clear, on: :collection
  end

  resources :carts do
    get :remove, on: :member
  end

  resources :orders, only: [:index, :show, :destroy, :create, :new]


  resources :products, only:[:show] do

  end

  get '/:category/:sub_category'=>'products#index', as: :category_products
  get '/:brand'=>'products#index', as: :brand_products



  resources :posts






  resources :reviews



  root 'home#index'
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController

  def index
    @wishlist = current_user.wishlists
  end

  def create

  end

  def delete

  end

  def clear

  end

end

app/views/wishlists/_form.html.erb
<%= form_for(@wishlist) do |f| %>
  <% if @wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% @wishlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.number_field :priority %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing Wishlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<div class="page-header">
  <h3>Wishlist Product</h3>
  <div class="actions">
    <% link_to clear_wishlists_path, class: '' do %>
        <i class="fa fa-trash" aria-hidden="true"></i>
    <% end %>
  </div>
</div>
<% if @wishlists.present? %>
    <ul class="product-list-small">
      <% wishlists.each do |product| %>
          <li>
            <%= link_to product_path(product.product), class:'product-photo' do%>
                <%= image_tag( product.product.image.present? ? product.product.image_url(:thumb) : "default_product_icon.png"  ) %>
            <% end %>

            <h2><%= link_to product.product.name.upcase , product_path(product.product), class:'product-photo' %></h2>

            <a href="#" class="product-compare">compare</a>

            <div class="product-rating">
              <div>
            <span class="product-stars" style="width: 60px" >
                <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
            </span>
              </div>
              <span><a href="#">82 reviews</a></span>
            </div>

            <p class="product-description">
              <%= truncate(product.product.description, length: 50) %>
            </p>

            <% if product.product.is_available %>
                <div class="btn-group add-to-cart" role="group" id="add-to-cart-<%= product.product.id %>">
                  <%=raw add_to_cart_text(product.product) %>
                </div>
            <% else %>
                <span class="product-out-of-stock">Out of stock</span>
            <% end %>
            <p class="product-price"> &#2547; <%= product.product.price %></p>

          </li>
      <% end %>
    </ul>
<% else %>
    <div class="no-products">
      <div class="no-products-message">
        <h2>There's no products. Please explore another category or brand..</h2>
      </div>
    </div>
<% end %>

app/views/wishlists/new.html.erb
<h1>New Wishlist</h1>

<%= render 'form' %>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @wishlist.product_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @wishlist.user_id %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @wishlist.priority %>
</p>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>